version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: userocean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kafka123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: userauth_app
    depends_on:
      - db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Kafka123
      JWT_SECRET: cok-uzun-ve-guvenli-bir-secret-key-1234567890
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userocean
    ports:
      - "8080:8080"

volumes:
  postgres_data: